version: '3.8'

services:
  nginx-proxy:
    build: .
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    volumes:
      # For live config updates without rebuild (optional)
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge